import Head from 'next/head'
import Card from '../components/Card'

export default function Home() {
    return (
        <div>
            <Head>
                <title>Zadanie 1</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div></div>
            <div className="flex flex-col py-16 lg:p-0 lg:flex-row justify-center lg:h-screen bg-gradient-to-b from-[#eeeff9] to-white">
                <div className="lg:w-1/2 flex items-center relative">
                    <div className="px-6 lg:ml-16 space-y-4 z-50 lg:w-[60%]">
                        <h3 className="text-md tracking-wide  text-[#5c6bc0]">
                            LOREM IPSUM
                        </h3>
                        <h1 className="text-5xl text-[#1a237e] tracking-wide leading-snug">
                            <span className="text-[#314efe]">Lorem ipsum </span>
                            dolor sit amet consectetur.
                        </h1>
                        <p className="text-[#5c6bc0] tracking-wide leading-6">
                            Suspendisse urna enim, varius nec ante id, cursus
                            sollicitudin elit. Praesent elit velit, consectetur
                            id massa sit amet, rhoncus aliquam ligula
                        </p>
                        <button className="bg-[#ffab02] px-4 py-2 rounded-md text-white shadow-md hover:scale-105 hover:shadow-lg active:scale-95 duration-150">
                            ACTION
                        </button>
                    </div>
                    <div className="absolute w-1/2 h-full lg:h-[60%] bottom-0 right-0 lg:left-0 rounded-bl-full lg:rounded-bl-none rounded-tl-full bg-gradient-to-b from-[#eeeff9] to-white"></div>
                </div>
                <div className="lg:w-1/2 md:py-20 p-6 flex flex-col md:flex-row space-y-14 md:space-y-0 md:space-x-14 items-center relative z-50 xl:p-6 2xl:p-12">
                    <div className="space-y-14 z-50 flex flex-col md:-mt-16">
                        <Card
                            iconColor="#1e88e5"
                            bgRgba="rgba(30, 136, 229, 0.4)"
                        />
                        <Card
                            iconColor="#f9a825"
                            bgRgba="rgba(249, 168, 37, 0.4)"
                        />
                    </div>
                    <div className="space-y-14 z-50 flex flex-col m-0">
                        <Card
                            iconColor="#43a048"
                            bgRgba="rgba(67, 160, 72, 0.4)"
                        />
                        <Card
                            iconColor="#8e25aa"
                            bgRgba="rgba(142, 37, 170, 0.4)"
                        />
                    </div>
                    <div className="absolute w-1/2 h-[60%] bottom-0 lg:top-0 right-0 rounded-tl-full lg:rounded-tl-none rounded-bl-full bg-gradient-to-b from-[#eff0f9] to-[#eeeff9]"></div>
                </div>
            </div>
        </div>
    )
}
// #1e88e5
